  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	activemq						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	adam-java-service						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	ai-assistant						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	apache-livy						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	autorail						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	awx-ee-custom						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	bifrost						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	clamav						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	clickhouse-data-manager						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	clinical-model-web						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	confluentinc/cp-enterprise-kafka						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	confluentinc/cp-zookeeper						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	cp-kafka-connect						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	danielqsj/kafka-exporter						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	datastage						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	db-migration						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	diff-migration-job						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	dna-cdc-etl						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	dna-platform						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	dpp-python-jobs						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	dwh-proxy						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	edc-migration-job						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	ehr-integration-flow-bridge						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	flower						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	freeipa-server						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	httproute-weights-updater						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	jetty						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	jsreport						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	juanluisbaptiste/postfix						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	jupyter-server						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	jupyterhub						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	krackend						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	mdr-admin-panel						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	msg-consumer						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	non-crf-data-collector						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	nphase-cdisc-spring						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	one-login-keycloak						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	one-login-users-sync						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	openjdk						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	papermill_microservice						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	rcc-standards-service						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	reporter-scheduler						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	rule-engine						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	sce-r-service						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	sce-reports-spring						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	sdtm-service						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	service-health						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	service-health-collector						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	sm-python-server						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	 	solsson/kafka-prometheus-jmx-exporter						
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	sonarqube-plugins
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	spark
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	superset
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	tenant-server
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	visual-flow
  	aws --profile nphase ecr get-lifecycle-policy  --repository-name    --region us-east-1	visual-flow-jobs
